// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is the build information exposed to the UI and to the CLI.
 */
export interface Info {
    "version": string;
    "commit": string;
    "date": string;
    "platform": string;
}
