// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfoService exposes the build information of the running binary.
 * 
 * It is the reference shape for every service that follows: it takes no input,
 * returns data ready to render, and carries nothing sensitive.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as version$0 from "../version/models.js";

/**
 * Info returns the version, commit, build date and platform of this build.
 */
export function Info(): $CancellablePromise<version$0.Info> {
    return $Call.ByID(4151165481);
}
