// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogService is the boundary the object tree is drawn from.
 * 
 * One level per call, because that is what lazy means here: expanding a node
 * asks what that node holds and nothing more. Reading a schema whole is a
 * different question with a different budget, and it belongs to the panel that
 * shows an object rather than to the tree that lists them.
 * 
 * No SQL crosses in either direction. What arrives is a place and a filter;
 * what goes back is a name, a kind and whether there is anything under it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Children answers what a node holds.
 * 
 * The context is the caller's: somebody who expands a node of a large schema
 * and gives up before it comes back stops the query rather than waiting for an
 * answer nobody wants any more.
 */
export function Children(id: string, node: $models.NodeRef, filter: $models.TreeFilter): $CancellablePromise<$models.NodeView[] | null> {
    return $Call.ByID(3638715734, id, node, filter);
}
