// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService is the boundary for everything to do with connecting.
 * 
 * The frontend never assembles a connection string and never sees a password
 * come back: it sends a form, and receives a diagnosis or a state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check contacts the server and returns the state it found.
 */
export function Check(id: string): $CancellablePromise<$models.StatusView> {
    return $Call.ByID(811747560, id);
}

/**
 * Close releases a connection.
 */
export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(144657044, id);
}

/**
 * Databases lists what the open connection may reach, which is how someone who
 * connected without naming a database chooses one.
 */
export function Databases(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1404509674, id);
}

/**
 * Open connects and keeps the connection, returning the identifier the window
 * uses to refer to it.
 */
export function Open(form: $models.ConnectionForm): $CancellablePromise<$models.StatusView> {
    return $Call.ByID(702103832, form);
}

/**
 * Parse fills the form from a pasted connection URI.
 * 
 * The password is deliberately left out even when the URI carried one. It came
 * from the window a moment ago, so echoing it back leaks nothing new — but it
 * would put the secret into the state of a page that is redrawn, inspected and
 * occasionally screenshotted, and HasPassword tells the form what it needs to
 * know without that.
 */
export function Parse(uri: string): $CancellablePromise<$models.ConnectionView> {
    return $Call.ByID(699417983, uri);
}

/**
 * SSLModes lists the modes the form offers, so that the list lives in one place
 * rather than being retyped in the window.
 */
export function SSLModes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(480654570);
}

/**
 * Status returns the last known state without contacting the server, which is
 * what the window calls as it redraws.
 */
export function Status(id: string): $CancellablePromise<$models.StatusView> {
    return $Call.ByID(2570429330, id);
}

/**
 * Test tries the connection and explains what happened.
 * 
 * It always returns a diagnosis rather than an error: a failure to connect is
 * the expected outcome of a test, and the whole point of this task is that the
 * window shows something a person can act on instead of a driver message.
 */
export function Test(form: $models.ConnectionForm): $CancellablePromise<$models.DiagnosisView> {
    return $Call.ByID(2285711796, form);
}
