// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService is the boundary for everything to do with connecting.
 * 
 * The frontend never assembles a connection string and never sees a password
 * come back: it sends a form, and receives a diagnosis or a state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check contacts the server and returns the state it found.
 */
export function Check(id: string): $CancellablePromise<$models.StatusView> {
    return $Call.ByID(811747560, id);
}

/**
 * Close releases a connection.
 */
export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(144657044, id);
}

/**
 * CloseAll releases every open connection. The window calls it on shutdown, so
 * that reloading or quitting does not leave pools alive until the process dies.
 */
export function CloseAll(): $CancellablePromise<void> {
    return $Call.ByID(2364498479);
}

/**
 * Databases lists what the open connection may reach, which is how someone who
 * connected without naming a database chooses one.
 */
export function Databases(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1404509674, id);
}

/**
 * Delete removes a connection and the password that belonged to it.
 * 
 * Both, because a secret left behind is an item in the keychain of the person
 * that nothing will ever look for again: invisible litter that outlives the
 * application.
 * 
 * The password goes first, which is the mirror of the order Save uses and the
 * same argument. Either order can fail halfway, so the question is which
 * half-done state a person can get out of. Removing the connection first fails
 * into a secret nothing points at any more — unreachable from here, with no
 * second Forget to press, because the connection it belonged to is gone.
 * Removing the password first fails into a connection that is still listed and
 * still has its Forget button: the operation can simply be repeated, and the
 * second attempt finds no secret and says so is normal.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1974899595, id);
}

/**
 * List returns the saved connections, and touches no keychain doing it.
 */
export function List(): $CancellablePromise<$models.SavedView[] | null> {
    return $Call.ByID(2303624856);
}

/**
 * Open connects and keeps the connection, returning the identifier the window
 * uses to refer to it.
 */
export function Open(form: $models.ConnectionForm): $CancellablePromise<$models.StatusView> {
    return $Call.ByID(702103832, form);
}

/**
 * Parse fills the form from a pasted connection URI.
 * 
 * The password is deliberately left out even when the URI carried one. It came
 * from the window a moment ago, so echoing it back leaks nothing new — but it
 * would put the secret into the state of a page that is redrawn, inspected and
 * occasionally screenshotted, and HasPassword tells the form what it needs to
 * know without that.
 */
export function Parse(uri: string): $CancellablePromise<$models.ConnectionView> {
    return $Call.ByID(699417983, uri);
}

/**
 * SSLModes lists the modes the form offers, so that the list lives in one place
 * rather than being retyped in the window.
 */
export function SSLModes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(480654570);
}

/**
 * Save keeps a connection: the connection in the file, its password in the
 * keychain, and never one of them in the other.
 * 
 * A form with no identifier is a new connection and is given one. A form that
 * carries one replaces the connection it names, which is what editing is.
 */
export function Save(form: $models.ConnectionForm): $CancellablePromise<$models.SavedView> {
    return $Call.ByID(4137694157, form);
}

/**
 * Status returns the last known state without contacting the server, which is
 * what the window calls as it redraws.
 */
export function Status(id: string): $CancellablePromise<$models.StatusView> {
    return $Call.ByID(2570429330, id);
}

/**
 * Test tries the connection and explains what happened.
 * 
 * It always returns a diagnosis rather than an error: a failure to connect is
 * the expected outcome of a test, and the whole point of this task is that the
 * window shows something a person can act on instead of a driver message.
 */
export function Test(form: $models.ConnectionForm): $CancellablePromise<$models.DiagnosisView> {
    return $Call.ByID(2285711796, form);
}

/**
 * VaultStatus says where passwords are being kept.
 * 
 * The window asks so that it can say so, and warn when the answer is that they
 * are not being kept at all. A vault that silently forgets is exactly the
 * failure this boundary exists to make visible.
 * 
 * It takes a context and can fail because the answer may still be on its way:
 * the store of the operating system is opened in the background so that the
 * window does not wait for it, and this is the call that waits instead — after
 * the window is already drawn, where waiting costs nobody anything.
 */
export function VaultStatus(): $CancellablePromise<$models.VaultView> {
    return $Call.ByID(2574975934);
}
