// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JobService is what the window uses to see and stop what is running.
 * 
 * Every exported method here becomes a binding, which is why pushing lives in
 * JobWatcher and not on this type: Watch never returns, and a window able to
 * call it could hold a goroutine open for the life of the application by
 * accident. This half answers questions; the other half talks without being
 * asked.
 * 
 * It assembles no SQL and carries no credential: a job is a title, a state and
 * a number, and the log it hands over has already had its secrets taken out on
 * the way into the queue.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel asks a job to stop.
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(3459969595, id);
}

/**
 * Forget drops a job that has ended from the list.
 */
export function Forget(id: string): $CancellablePromise<void> {
    return $Call.ByID(113955724, id);
}

/**
 * List answers every job the window knows about.
 * 
 * It is the reconciliation half of ADR-0015: events are the fast path and this
 * is the truth. A window that missed an event is corrected by asking, and the
 * path that corrects it is the same one that filled the panel in the first
 * place — so it is exercised every time the panel opens, rather than only when
 * something has already gone wrong.
 */
export function List(): $CancellablePromise<$models.JobView[] | null> {
    return $Call.ByID(3462799265);
}

/**
 * Log answers everything a job has said.
 * 
 * The whole log, unlike the events, because this is what a panel being opened
 * on a job that has been running for ten minutes needs.
 */
export function Log(id: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2942170097, id);
}
