// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ColumnView is one column as the panel shows it.
 */
export interface ColumnView {
    /**
     * PrimaryKey says the column is part of the key of its table.
     * 
     * It is a fact handed over rather than one the window works out. The
     * alternative is reading "PRIMARY KEY (id)" out of the text of a constraint
     * and matching names against it, which is the frontend interpreting SQL —
     * the one thing this boundary exists to prevent, and wrong the first time a
     * column is called `id, note`.
     */
    "primaryKey": boolean;
    "name": string;
    "type": string;
    "notNull": boolean;
    "default": string;
    "identity": string;
    "generated": string;
    "collation": string;
}

/**
 * ConnectionForm is what the window sends when someone describes a connection.
 * 
 * It is the one type that carries a password, and it only ever travels inwards.
 * Nothing returned from this service has that field, which is why the form and
 * the view below are separate types rather than one shared struct with a rule
 * about when to blank a member.
 */
export interface ConnectionForm {
    /**
     * ID is empty for a connection being described for the first time and set
     * for one being edited. It decides whether Save adds a connection or
     * replaces one, and it is what the password is filed under in the keychain.
     */
    "id": string;
    "name": string;

    /**
     * Params are session parameters; Options are libpq connection settings.
     * Both are carried so that a pasted URI does not quietly lose them
     * between the parser and the connection.
     */
    "params": { [_ in string]?: string } | null;
    "options": { [_ in string]?: string } | null;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "password": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;

    /**
     * Environment is what this connection is — dev, staging or prod — and
     * empty for one nobody labelled. ReadOnly asks the server to refuse every
     * statement that writes.
     */
    "environment": string;
    "readOnly": boolean;
}

/**
 * ConnectionView is a connection as the window draws it. There is deliberately
 * no password field: a type that cannot carry a secret cannot leak one.
 */
export interface ConnectionView {
    "name": string;
    "params": { [_ in string]?: string } | null;
    "options": { [_ in string]?: string } | null;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;

    /**
     * HasPassword says the pasted URI carried one, so the form can ask for it
     * rather than pretend the connection is ready.
     */
    "hasPassword": boolean;
}

/**
 * DiagnosisView is a failure explained, ready to render.
 */
export interface DiagnosisView {
    "failed": boolean;
    "class": string;
    "summary": string;
    "cause": string;
    "nextStep": string;
    "detail": string;
}

/**
 * HistoryView says whether what runs is being remembered, and warns when it is
 * not.
 * 
 * The warning is prose because it is shown to a person and has to name the file
 * it is about. It is empty exactly when the history is being written, which is
 * what the window decides whether to draw a banner from.
 */
export interface HistoryView {
    "warning": string;
}

/**
 * JobCursor is where a page of the history stopped, as the window holds it.
 * 
 * The time crosses as the string it was drawn from rather than as a number,
 * so that the window hands back exactly what it was given and nothing has to
 * be reassembled from two halves that could disagree.
 */
export interface JobCursor {
    "endedAt": string;
    "id": string;
}

/**
 * JobProgressView is how far along a job is, as the window reads it.
 * 
 * Durations cross as milliseconds. A Go duration marshals as a count of
 * nanoseconds, which the window would have to know to divide by a billion —
 * and dividing by the wrong power of ten is invisible until an ETA reads three
 * hours for a job with three seconds left.
 */
export interface JobProgressView {
    "step": string;
    "unit": string;
    "done": number;
    "total": number;
    "fraction": number;
    "indeterminate": boolean;
    "elapsedMs": number;
    "remainingMs": number;
}

/**
 * JobView is a job as the window draws it.
 * 
 * The state crosses as its name. A number would make the frontend carry a copy
 * of an enumeration whose order is an implementation detail of a Go file, and
 * reordering the constants would silently relabel every row.
 * 
 * The times cross as strings, and an empty one means there is none. A job that
 * has not ended has no end, and the zero time rendered by a date formatter is
 * 1 January year 1 — which it will print rather than refuse.
 */
export interface JobView {
    "id": string;
    "kind": string;
    "title": string;
    "state": string;
    "error": string;
    "progress": JobProgressView;
    "dropped": number;
    "startedAt": string;
    "endedAt": string;
}

/**
 * NodeRef says which node of the tree is being opened.
 * 
 * It is a place rather than a query: the frontend names where it is and gets
 * back what is there. Empty is the server, a database alone is that database,
 * and a database with a schema is that schema. There is no fourth level in this
 * version, which is what Expandable says on the way out.
 */
export interface NodeRef {
    "database": string;
    "schema": string;
}

/**
 * NodeView is one row of the object tree.
 */
export interface NodeView {
    "kind": string;
    "name": string;
    "expandable": boolean;
}

/**
 * ObjectRef names one object of one schema of one database.
 */
export interface ObjectRef {
    "database": string;
    "schema": string;
    "name": string;
}

/**
 * PropertiesView is what an object is, for the panel beside the tree.
 * 
 * It carries text the window prints rather than the model itself. The model is
 * the shape the diff compares, it changes for reasons that have nothing to do
 * with what a person reads, and a panel bound to it would drag every one of
 * those changes across the boundary.
 */
export interface PropertiesView {
    "kind": string;
    "name": string;
    "columns": ColumnView[] | null;
    "constraints": string[] | null;
    "indexes": string[] | null;

    /**
     * Notes are the facts about an object that are not a column: that it is
     * unlogged, that it is a partition, that row security is on. Text, because
     * a person reads them and nothing branches on them.
     */
    "notes": string[] | null;
}

/**
 * SavedView is a saved connection as the window lists it.
 * 
 * It is a type of its own rather than ConnectionView with an identifier added,
 * because the two answer different questions. ConnectionView reports what a
 * pasted URI contained, HasPassword included. This reports what is in the file,
 * and the file cannot say whether a password is in the keychain: finding out
 * would mean reading the keychain once per row, which on macOS and on Linux is
 * an authorisation dialog per connection for someone who wanted to see a list.
 */
export interface SavedView {
    "id": string;
    "name": string;
    "params": { [_ in string]?: string } | null;
    "options": { [_ in string]?: string } | null;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;
    "environment": string;
    "readOnly": boolean;
    "archived": boolean;
}

/**
 * StatusView is the state of an open connection, and who that connection is.
 * 
 * The three fields after the state are the ones that make a production server
 * unmistakable in every tab. A tab cannot arrange that for itself — it can only
 * draw what it was handed — so the label travels with the state rather than
 * being looked up separately by whoever remembers to.
 */
export interface StatusView {
    /**
     * ID addresses this connection while it is open. It is minted when the
     * connection opens and means nothing to the file.
     */
    "id": string;

    /**
     * SavedID is the connection in the file this was opened from, and empty for
     * one opened from a form that was never saved.
     * 
     * The two are never equal, so a window that compared them would have a list
     * in which nothing is ever marked as open, and would open a second
     * connection to a server that already has one.
     */
    "savedId": string;
    "state": string;
    "diagnosis": DiagnosisView;
    "name": string;
    "environment": string;
    "readOnly": boolean;

    /**
     * Where the connection goes, so that a window can say which database and
     * which role it is looking at without asking a second question. None of it
     * is a secret — it is what the form was filled in with, minus the one field
     * that is.
     */
    "host": string;
    "port": number;
    "database": string;
    "user": string;
}

/**
 * TreeFilter narrows a level before it crosses.
 * 
 * It is applied by the server, not here. A level of fifty thousand names
 * carried across so that most of them could be dropped is the waste the whole
 * listing exists to avoid — and the pattern travels as an argument beside the
 * query, never inside it.
 */
export interface TreeFilter {
    /**
     * Pattern matches an object name as a case-insensitive substring. It
     * applies to the objects of a schema and to nothing else: narrowing the
     * schemas themselves would hide the schema that holds the match, which is
     * the opposite of what somebody typing a name is asking for.
     */
    "pattern": string;

    /**
     * System includes the schemas PostgreSQL keeps for itself. It means
     * nothing at the other levels.
     */
    "system": boolean;
}

/**
 * VaultView says where passwords are being kept, and warns when the honest
 * answer is "until Hermes quits".
 * 
 * The warning is prose because it is shown to a person and has to name what to
 * install. It is empty exactly when the keychain of the system is in use, which
 * is what the window decides whether to draw a banner from.
 */
export interface VaultView {
    "backend": string;
    "warning": string;
}
