// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionForm is what the window sends when someone describes a connection.
 * 
 * It is the one type that carries a password, and it only ever travels inwards.
 * Nothing returned from this service has that field, which is why the form and
 * the view below are separate types rather than one shared struct with a rule
 * about when to blank a member.
 */
export interface ConnectionForm {
    /**
     * ID is empty for a connection being described for the first time and set
     * for one being edited. It decides whether Save adds a connection or
     * replaces one, and it is what the password is filed under in the keychain.
     */
    "id": string;
    "name": string;

    /**
     * Params are session parameters; Options are libpq connection settings.
     * Both are carried so that a pasted URI does not quietly lose them
     * between the parser and the connection.
     */
    "params": { [_ in string]?: string } | null;
    "options": { [_ in string]?: string } | null;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "password": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;
}

/**
 * ConnectionView is a connection as the window draws it. There is deliberately
 * no password field: a type that cannot carry a secret cannot leak one.
 */
export interface ConnectionView {
    "name": string;
    "params": { [_ in string]?: string } | null;
    "options": { [_ in string]?: string } | null;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;

    /**
     * HasPassword says the pasted URI carried one, so the form can ask for it
     * rather than pretend the connection is ready.
     */
    "hasPassword": boolean;
}

/**
 * DiagnosisView is a failure explained, ready to render.
 */
export interface DiagnosisView {
    "failed": boolean;
    "class": string;
    "summary": string;
    "cause": string;
    "nextStep": string;
    "detail": string;
}

/**
 * SavedView is a saved connection as the window lists it.
 * 
 * It is a type of its own rather than ConnectionView with an identifier added,
 * because the two answer different questions. ConnectionView reports what a
 * pasted URI contained, HasPassword included. This reports what is in the file,
 * and the file cannot say whether a password is in the keychain: finding out
 * would mean reading the keychain once per row, which on macOS and on Linux is
 * an authorisation dialog per connection for someone who wanted to see a list.
 */
export interface SavedView {
    "id": string;
    "name": string;
    "params": { [_ in string]?: string } | null;
    "options": { [_ in string]?: string } | null;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;
    "archived": boolean;
}

/**
 * StatusView is the state of an open connection.
 */
export interface StatusView {
    "id": string;
    "state": string;
    "diagnosis": DiagnosisView;
}

/**
 * VaultView says where passwords are being kept, and warns when the honest
 * answer is "until Hermes quits".
 * 
 * The warning is prose because it is shown to a person and has to name what to
 * install. It is empty exactly when the keychain of the system is in use, which
 * is what the window decides whether to draw a banner from.
 */
export interface VaultView {
    "backend": string;
    "warning": string;
}
