// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionForm is what the window sends when someone describes a connection.
 * 
 * It is the one type that carries a password, and it only ever travels inwards.
 * Nothing returned from this service has that field, which is why the form and
 * the view below are separate types rather than one shared struct with a rule
 * about when to blank a member.
 */
export interface ConnectionForm {
    "name": string;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "password": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;
}

/**
 * ConnectionView is a connection as the window draws it. There is deliberately
 * no password field: a type that cannot carry a secret cannot leak one.
 */
export interface ConnectionView {
    "name": string;
    "host": string;
    "port": number;
    "database": string;
    "user": string;
    "sslMode": string;
    "rootCert": string;
    "cert": string;
    "key": string;

    /**
     * HasPassword says the pasted URI carried one, so the form can ask for it
     * rather than pretend the connection is ready.
     */
    "hasPassword": boolean;
}

/**
 * DiagnosisView is a failure explained, ready to render.
 */
export interface DiagnosisView {
    "failed": boolean;
    "class": string;
    "summary": string;
    "cause": string;
    "nextStep": string;
    "detail": string;
}

/**
 * StatusView is the state of an open connection.
 */
export interface StatusView {
    "id": string;
    "state": string;
    "diagnosis": DiagnosisView;
}
