//go:build integration

package testsupport

import (
	"fmt"
	"strings"
	"sync/atomic"
	"testing"
)

// The corpus of pathological schemas: the fixture the catalog, the DDL writer
// and the diff are all measured against.
//
// It is not a happy path with a few extras. Every entry is here because it has
// broken a tool that reads catalogs, and because a reader that handles the
// ordinary case and not these is a reader whose diff produces noise on the
// first real database it meets. The testing strategy lists what it has to
// contain; this is that list, made.
//
// It grows with the phases that read it. A phase that adds a query adds the
// objects that query is about, so that no fixture is written for something
// nothing yet looks at — a fixture nobody reads is a fixture nobody notices is
// wrong.

// corpusSequence keeps two calls from colliding. The container is shared by
// every test in the binary and outlives all of them, so a fixed schema name is
// a schema that is already there the second time anything creates it.
var corpusSequence atomic.Uint64

// Corpus creates the pathological schema and answers its name.
//
// A schema of its own per call rather than one shared: creating it is DDL on a
// container that is already running, which costs milliseconds, and sharing it
// would make one test's failure show up in another's.
func Corpus(t *testing.T, instance *Instance) string {
	t.Helper()

	schema := fmt.Sprintf("corpus_%d", corpusSequence.Add(1))

	instance.Exec(t, "CREATE SCHEMA "+schema)

	// Not dropped when the test ends, and that is not an omission. Exec runs
	// through the context of the test, which is already cancelled by the time a
	// cleanup runs — a drop registered here fails every time and reports a
	// second problem on top of whatever the test found. The container is the
	// cleanup: it is thrown away at the end of the run, and the name carries a
	// counter so no two calls collide inside one.
	for _, statement := range corpusStatements {
		instance.Exec(t, strings.ReplaceAll(statement, schemaToken, schema))
	}

	return schema
}

// schemaToken is what stands in for the schema in the statements below.
//
// A token replaced by name rather than a format verb: several of these mention
// the schema more than once, and a count that drifts from the arguments is a
// fixture that fails to build for a reason that has nothing to do with what it
// was written to prove.
const schemaToken = "{schema}"

// The statements, each naming the schema through schemaToken.
//
// Ordered so that what a later one depends on already exists, which is the same
// order the dependency phase will later have to work out for itself.
var corpusStatements = []string{
	// Names that need quoting, in three ways that each broke something once:
	// upper case, which folds if it is not quoted; a space, which ends the
	// identifier; and an accent, which is more than one byte and sorts
	// differently under every locale.
	`CREATE TABLE {schema}."Customer" (
		id integer PRIMARY KEY,
		"Full Name" text NOT NULL,
		"endereço" text
	)`,

	// A type of their own, which must not be folded into a built-in.
	`CREATE TYPE {schema}.mood AS ENUM ('sad', 'ok', 'happy')`,
	`CREATE DOMAIN {schema}.positive AS integer CHECK (VALUE > 0)`,
	`CREATE TYPE {schema}.pair AS (first integer, second text)`,

	// Every shape a column can have that the model has a field for. The
	// defaults are deliberately of different kinds — a literal, a cast, a
	// function call — because they render differently and the canonical form
	// has to survive all three.
	`CREATE TABLE {schema}.column_shapes (
		id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		by_default integer GENERATED BY DEFAULT AS IDENTITY,
		plain_default integer DEFAULT 42,
		cast_default text DEFAULT 'x'::text,
		called_default timestamp with time zone DEFAULT now(),
		generated_column integer GENERATED ALWAYS AS (plain_default * 2) STORED,
		collated text COLLATE "C",
		nullable text,
		not_nullable text NOT NULL,
		typed {schema}.mood,
		domained {schema}.positive,
		composite {schema}.pair,
		numbers integer[],
		matrix integer[][]
	)`,

	// The spellings of one type. Every one of these is an alias, and a reader
	// that stored what was written would report six type changes between this
	// table and one declared the long way.
	`CREATE TABLE {schema}.type_aliases (
		a int4,
		b int,
		c int2,
		d int8,
		e bool,
		f float4,
		g float8,
		h varchar(50),
		i decimal(10,2),
		j timestamptz,
		k timestamp,
		l timetz,
		m time,
		n char(3),
		o serial
	)`,

	// Inheritance, which is not partitioning and is read as its own thing.
	`CREATE TABLE {schema}.parent (id integer PRIMARY KEY, common text)`,
	`CREATE TABLE {schema}.child (extra text) INHERITS ({schema}.parent)`,

	// Declarative partitioning. The partitions are tables in their own right,
	// which is what this proves the reader survives.
	`CREATE TABLE {schema}.measurements (
		id integer NOT NULL,
		taken date NOT NULL
	) PARTITION BY RANGE (taken)`,
	`CREATE TABLE {schema}.measurements_2026 PARTITION OF {schema}.measurements
		FOR VALUES FROM ('2026-01-01') TO ('2027-01-01')`,

	// A dropped column. PostgreSQL leaves the entry in pg_attribute so the row
	// layout does not move, and a reader that does not skip it puts a column
	// called ........pg.dropped.2........ in the model.
	`CREATE TABLE {schema}.with_a_hole (id integer, gone text, kept text)`,
	`ALTER TABLE {schema}.with_a_hole DROP COLUMN gone`,

	// A table with no columns at all is legal, and it is the shape that finds
	// a reader which assumes every table joins to at least one row.
	`CREATE TABLE {schema}.empty_table ()`,
}
