//go:build integration

package testsupport

import (
	"fmt"
	"strconv"
	"strings"
	"testing"
)

// LargeSchema creates a schema of the given size and answers its name.
//
// It is the fixture the performance budget is measured against, and it is a
// different thing from the corpus: the corpus is small and strange, made of the
// shapes that break a reader, while this is ordinary and big, made of the shape
// a real database has a thousand of. A budget measured against the corpus would
// say nothing, and a correctness suite run against this would say nothing
// either.
//
// Ordinary does not mean bare. Every table has a key, an identity column, an
// index of its own and a foreign key to the one before it, and every tenth has
// a view over it — so the reading has constraints, indexes, sequences, views
// and a thousand edges to assemble, which is what the budget is about. A
// thousand tables of two columns each would measure a query planner and call it
// introspection.
func LargeSchema(tb testing.TB, instance *Instance, tables int) string {
	tb.Helper()

	schema := fmt.Sprintf("large_%d", corpusSequence.Add(1))

	instance.Exec(tb, "CREATE SCHEMA "+schema)

	// In blocks rather than one statement for the whole schema, and rather than
	// one statement per table. Each Exec is a process started inside the
	// container, so a table at a time would spend minutes building the fixture
	// of a test whose budget is measured in seconds; but a DO block is one
	// transaction, and every table it creates holds locks on the table, its
	// index and its sequence until that transaction ends. Five thousand of them
	// exhausted max_locks_per_transaction on the oldest server in the matrix and
	// took the fixture down with an error about the server's configuration —
	// which is a fact about building the fixture and not about anything the
	// product does.
	for from := 1; from <= tables; from += blockOfTables {
		to := min(from+blockOfTables-1, tables)

		instance.Exec(tb, strings.NewReplacer(
			schemaToken, schema,
			"{from}", strconv.Itoa(from),
			"{to}", strconv.Itoa(to),
		).Replace(largeSchema))
	}

	return schema
}

// blockOfTables is how many tables are created per transaction. It is well
// under the lock budget of a default server and well over the point where the
// cost of starting another process inside the container matters.
const blockOfTables = 500

// largeSchema builds the tables in the server rather than in Go.
//
// The identifiers go through format's %I, which is the server's own quoting, so
// the loop cannot produce a broken statement for a name it generated. The
// schema is substituted before the statement is sent — it is a name this
// package made and not one anybody typed.
const largeSchema = `DO $$
DECLARE
	present text;
BEGIN
	FOR i IN {from}..{to} LOOP
		present := 't_' || i;

		EXECUTE format('CREATE TABLE {schema}.%I (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label text NOT NULL,
			amount numeric(12,2) DEFAULT 0,
			made timestamp with time zone DEFAULT now(),
			parent integer)', present);

		EXECUTE format('CREATE INDEX %I ON {schema}.%I (label)', present || '_label', present);

		-- The table before this one, worked out from the number rather than
		-- carried in a variable: the blocks are separate statements, so a
		-- variable would forget the chain at every boundary and the fixture
		-- would lose one foreign key per block.
		IF i > 1 THEN
			EXECUTE format('ALTER TABLE {schema}.%I ADD CONSTRAINT %I
				FOREIGN KEY (parent) REFERENCES {schema}.%I (id)',
				present, present || '_parent_fkey', 't_' || (i - 1));
		END IF;

		IF i % 10 = 0 THEN
			EXECUTE format('CREATE VIEW {schema}.%I AS SELECT id, label FROM {schema}.%I',
				'v_' || i, present);
		END IF;
	END LOOP;
END $$`
