//go:build integration

package testsupport

import (
	"fmt"
	"strconv"
	"strings"
	"testing"
)

// LargeSchema creates a schema of the given size and answers its name.
//
// It is the fixture the performance budget is measured against, and it is a
// different thing from the corpus: the corpus is small and strange, made of the
// shapes that break a reader, while this is ordinary and big, made of the shape
// a real database has a thousand of. A budget measured against the corpus would
// say nothing, and a correctness suite run against this would say nothing
// either.
//
// Ordinary does not mean bare. Every table has a key, an identity column, an
// index of its own and a foreign key to the one before it, and every tenth has
// a view over it — so the reading has constraints, indexes, sequences, views
// and a thousand edges to assemble, which is what the budget is about. A
// thousand tables of two columns each would measure a query planner and call it
// introspection.
func LargeSchema(tb testing.TB, instance *Instance, tables int) string {
	tb.Helper()

	schema := fmt.Sprintf("large_%d", corpusSequence.Add(1))

	instance.Exec(tb, "CREATE SCHEMA "+schema)

	// One statement for the whole schema rather than one per table. Each Exec
	// is a process started inside the container, so a thousand of them would
	// spend minutes on the fixture of a test whose budget is five seconds — and
	// the server builds the schema far faster than anything can ask it to a
	// thousand times.
	statement := strings.NewReplacer(
		schemaToken, schema,
		"{tables}", strconv.Itoa(tables),
	).Replace(largeSchema)

	instance.Exec(tb, statement)

	return schema
}

// largeSchema builds the tables in the server rather than in Go.
//
// The identifiers go through format's %I, which is the server's own quoting, so
// the loop cannot produce a broken statement for a name it generated. The
// schema is substituted before the statement is sent — it is a name this
// package made and not one anybody typed.
const largeSchema = `DO $$
DECLARE
	previous text;
	present text;
BEGIN
	FOR i IN 1..{tables} LOOP
		present := 't_' || i;

		EXECUTE format('CREATE TABLE {schema}.%I (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			label text NOT NULL,
			amount numeric(12,2) DEFAULT 0,
			made timestamp with time zone DEFAULT now(),
			parent integer)', present);

		EXECUTE format('CREATE INDEX %I ON {schema}.%I (label)', present || '_label', present);

		IF previous IS NOT NULL THEN
			EXECUTE format('ALTER TABLE {schema}.%I ADD CONSTRAINT %I
				FOREIGN KEY (parent) REFERENCES {schema}.%I (id)',
				present, present || '_parent_fkey', previous);
		END IF;

		IF i % 10 = 0 THEN
			EXECUTE format('CREATE VIEW {schema}.%I AS SELECT id, label FROM {schema}.%I',
				'v_' || i, present);
		END IF;

		previous := present;
	END LOOP;
END $$`
